# Generated by Django 6.0.3 on 2026-03-11 15:31

import django.db.models.deletion
from django.db import migrations, models


def create_memberships(apps, schema_editor):
    UserProfile = apps.get_model("accounts", "UserProfile")
    OrganizationMembership = apps.get_model("accounts", "OrganizationMembership")
    for profile in UserProfile.objects.filter(organization__isnull=False):
        OrganizationMembership.objects.get_or_create(
            user=profile,
            organization=profile.organization,
            defaults={"role": profile.role, "is_primary": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.organization'),
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('agent', 'Agent'), ('viewer', 'Viewer')], default='agent', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_memberships', to='accounts.userprofile')),
            ],
            options={
                'unique_together': {('user', 'organization')},
            },
        ),
        migrations.RunPython(create_memberships, migrations.RunPython.noop),
    ]
