# Generated by Django 6.0.3

import secrets

from django.contrib.auth.hashers import make_password
from django.db import migrations, models


def set_initial_passwords(apps, schema_editor):
    UserProfile = apps.get_model("accounts", "UserProfile")
    for u in UserProfile.objects.all():
        u.password = make_password(secrets.token_urlsafe(32))
        u.save(update_fields=["password"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="password",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
        migrations.RunPython(set_initial_passwords, noop_reverse),
        migrations.RemoveField(
            model_name="userprofile",
            name="firebase_uid",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
