# Generated by Django 6.0.3 on 2026-04-27 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_firebase_add_password'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('trigger_type', models.CharField(choices=[('lead_stage_change', 'Lead moves to stage')], default='lead_stage_change', max_length=50)),
                ('action_type', models.CharField(choices=[('create_task', 'Create a task')], default='create_task', max_length=50)),
                ('action_title', models.CharField(help_text='Task title. Use {contact} and {stage} as placeholders.', max_length=255)),
                ('action_due_days', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='accounts.organization')),
                ('trigger_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automations', to='crm.pipelinestage')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
