# Generated by Django 6.0.3 on 2026-05-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_add_automation'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, upload_to='documents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='firebase_storage_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
