# Generated by Django 6.0.3 on 2026-05-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_document_file_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='automation',
            name='action_title',
            field=models.CharField(blank=True, help_text='Task title. Use {contact} and {stage} as placeholders.', max_length=255),
        ),
        migrations.AlterField(
            model_name='automation',
            name='action_type',
            field=models.CharField(choices=[('create_task', 'Create a task'), ('send_reminder', 'Send reminder'), ('update_status', 'Update status')], default='create_task', max_length=50),
        ),
        migrations.AlterField(
            model_name='automation',
            name='trigger_type',
            field=models.CharField(choices=[('lead_stage_change', 'Lead moves to stage'), ('policy_expiring_30', 'Policy expires in 30 days'), ('lead_inactive_7', 'Lead inactive for 7 days'), ('new_contact', 'New contact added')], default='lead_stage_change', max_length=50),
        ),
    ]
